In [1]:
import numpy as np

In [29]:
arr = np.array(
[
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [4, 4, 4, 4]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [4, 4, 4, 4]
    ]
]
)

In [30]:
arr.ndim

3

In [31]:
arr.shape 

(2, 3, 4)

In [32]:
arr.size

24

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr.itemsize

4

In [43]:
arr.size * arr.itemsize

96

In [49]:
arr.nbytes

96

In [106]:
np.arange(10, 20, 5)

array([10, 15])

In [99]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [136]:
a = 0
b = 5
k = 2 
np.linspace(a, b, (b-a) * k + 1)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [152]:
a = np.array([[(4, 2), (4, 5), (7, 8)], [(4, 2), (4, 5), (7, 8)]])


array(1)

In [153]:
np.array([(1 , 1), (0, 1)]) @ np.array([(2, 0), (3, 4)])

array([[5, 4],
       [3, 4]])

In [157]:
np.array([(3, 5, 6, 5), (7, 8, 9, 5)]) @ np.array([(4, 1), (1, 4), (2, 2), (1, 1)])

array([[34, 40],
       [59, 62]])

In [189]:
A = np.array([(3, 5, 6), (7, 8, 9), (1, 9, 5)]) 
B = np.array([(4, 1, 3), (1, 4, 3), (2, 2, 3), ])
A @ B

array([[29, 35, 42],
       [54, 57, 72],
       [23, 47, 45]])

In [190]:
(3 * A) @ B

array([[ 87, 105, 126],
       [162, 171, 216],
       [ 69, 141, 135]])

In [191]:
3 * (A @ B)

array([[ 87, 105, 126],
       [162, 171, 216],
       [ 69, 141, 135]])

In [192]:
C = B = np.array([(9, 8, 7), (6, 5, 4), (3, 2, 1), ])
C

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [193]:
A.shape, B.shape, C.shape

((3, 3), (3, 3), (3, 3))

In [194]:
(A @ B) @ C

array([[1182,  999,  816],
       [2196, 1854, 1512],
       [1224, 1035,  846]])

In [196]:
A @ (B @ C)

array([[1182,  999,  816],
       [2196, 1854, 1512],
       [1224, 1035,  846]])

In [199]:
A * (C + B)

array([[54, 80, 84],
       [84, 80, 72],
       [ 6, 36, 10]])

In [200]:
A * B + A * C

array([[54, 80, 84],
       [84, 80, 72],
       [ 6, 36, 10]])

In [203]:
(A + B) * C

array([[108, 104,  91],
       [ 78,  65,  52],
       [ 12,  22,   6]])

In [202]:
# (A+B)⋅C=A⋅C+B⋅C
A * C + B * C

array([[108, 104,  91],
       [ 78,  65,  52],
       [ 12,  22,   6]])

In [228]:
A, A.shape

(array([[3, 5, 6],
        [7, 8, 9],
        [1, 9, 5]]), (3, 3))

In [219]:
O_3x1 = np.ones(A.shape[1], dtype = 'int').reshape(A.shape[1], 1)
O_3x1, O_3x1.shape

(array([[1],
        [1],
        [1]]), (3, 1))

In [225]:
O_1x3 = np.ones(A.shape[0], dtype = 'int').reshape(1, A.shape[0])
O_1x3, O_1x3.shape

(array([[1, 1, 1]]), (1, 3))

In [229]:
O_1x3 @ A  

array([[11, 22, 20]])

In [230]:
A @ O_3x1

array([[14],
       [24],
       [15]])

In [213]:
np.ones(A.shape[0], dtype = 'int').reshape(1, A.shape[0]) @ A 

array([[11, 22, 20]])

In [233]:
E = np.array([(1, 0 , 0), (0, 1, 0), (0, 0, 1)])
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [234]:
A @ E

array([[3, 5, 6],
       [7, 8, 9],
       [1, 9, 5]])

In [235]:
E @ A

array([[3, 5, 6],
       [7, 8, 9],
       [1, 9, 5]])

In [237]:
E @ A == A @ E

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [238]:
A - A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [245]:
np.arange(6).reshape((2,3)) @ np.arange(6).reshape((3,2))

array([[10, 13],
       [28, 40]])

In [247]:
np.zeros((5, ))

array([0., 0., 0., 0., 0.])

In [273]:
np.zeros(5).shape

(5,)