In [1]:
import numpy as np

# Вычисления с массивами


## вычисления над каждым элементом одномерного массива (можно над любым измерением):

In [2]:
np.array([2, 3, 4, 5, 10, 100]) % 100

array([ 2,  3,  4,  5, 10,  0], dtype=int32)

## вычисления меджу массивами:

In [3]:
(np.array([5, 6, 7]) * np.array([1, 5, 10]))

array([ 5, 30, 70])

In [4]:
arr = np.array([
    [2, 5, 6],
    [5, 6, 8,],
    [9, 0, 4],
    [7, 9, 4],])

# Срезы массивов

In [5]:
# в квадратных скобках указывается срез сначало для строк, затем для столбцов
arr[::-2, ::2]

array([[7, 4],
       [5, 8]])

In [6]:
arr[1:-1, 1:-1]

array([[6],
       [0]])

In [7]:
# arr.argmin() - находит позиция в массиве с минимальным значением
print(arr)

print(
    'min value =', arr.item(arr.argmin()), 
    ', absolute position = ', arr.argmin(),
    ', index =', arr.argmin() // arr.shape[1],
    ', column =', arr.argmin() % arr.shape[1],
    f', value at position "arr[{arr.argmin() // arr.shape[1]}, {arr.argmin() % arr.shape[1]}]" =',
    arr[arr.argmin() // arr.shape[1], arr.argmin() % arr.shape[1]]
    )

# arr.argmax() - находит позицию в массиве с максимальным значением
print(
    'max value =', arr.item(arr.argmax()), 
    ', absolute position = ', arr.argmax(),
    ', index =', arr.argmax() // arr.shape[1],
    ', column =', arr.argmax() % arr.shape[1],
    f', value at position "arr[{arr.argmax() // arr.shape[1]}, {arr.argmax() % arr.shape[1]}]" =',
    arr[arr.argmax() // arr.shape[1], arr.argmax() % arr.shape[1]]
    )

[[2 5 6]
 [5 6 8]
 [9 0 4]
 [7 9 4]]
min value = 0 , absolute position =  7 , index = 2 , column = 1 , value at position "arr[2, 1]" = 0
max value = 9 , absolute position =  6 , index = 2 , column = 0 , value at position "arr[2, 0]" = 9


In [8]:
# np.arange(2, 9, .5) - генератор массивов "2" - начало интервала
# "9" - завершение интервала без включения, ".5" - шаг
print(np.arange(2, 9, .5))

print(np.arange(0, 2*8*2, 2))
print(np.arange(0, 2*8*2, 2).reshape(4,4))

print('\nНулевая матрица')
print(np.zeros((10, 3)))

print('\nМатрица из единиц')
print(np.zeros((3, 10)))


print('\nЕдиничная матрица - должна быть квадратной NxN')
print(np.eye(5))

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]

Нулевая матрица
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Матрица из единиц
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Единичная матрица - должна быть квадратной NxN
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Булевые операции (сравение, фильтры)

In [9]:
ages = np.random.randint(10,80, 30).reshape(6, 5)
print(ages)

workers = (ages > 18) & (ages < 68)
print(workers * 1)
print(
    'Total (of "True")', workers.sum(),
    '\nsum by row', workers.sum(axis=1),
    '\nsum by col', workers.sum(axis=0),
    )
print()
not_workers = (ages <= 18) | (ages >= 68)
print(not_workers * 1)
print(
    'Total (of "True")', not_workers.sum(),
    '\nsum by row', not_workers.sum(axis=1),
    '\nsum by col', not_workers.sum(axis=0),
    )


[[45 35 79 34 16]
 [76 45 79 26 69]
 [77 74 60 51 76]
 [33 13 16 30 30]
 [31 26 33 55 13]
 [55 67 31 59 79]]
[[1 1 0 1 0]
 [0 1 0 1 0]
 [0 0 1 1 0]
 [1 0 0 1 1]
 [1 1 1 1 0]
 [1 1 1 1 0]]
Total (of "True") 18 
sum by row [3 2 2 3 4 4] 
sum by col [4 4 3 6 1]

[[0 0 1 0 1]
 [1 0 1 0 1]
 [1 1 0 0 1]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]
Total (of "True") 12 
sum by row [2 3 3 2 1 1] 
sum by col [2 2 3 0 5]


In [10]:
ages[(ages<=18) | (ages > 68)]

array([79, 16, 76, 79, 69, 77, 74, 76, 13, 16, 13, 79])

# Приведение значений массива к логарифмической шкале

часто бывает необходимо отобразить на графике значения в удобном вормате таким образом, что бы не потерять разброс среди чисел массива. Наример мин = 10 000 и макс = 700 000 значения в массиве отличается на 690 000 или в 70 раз - если отобразить значения на одном графике, то большой разброс сравняет все числа в районе минимального значения. В таком случае часто прибегают к отображению данных на логарифмической шкале - в преведенном выше примере, разброс чисел между максимальным и минимальным значением уже не будет столь велико, при этом соотношения между величинами будут заметны


In [11]:
np.log(
    np.array(
        [
            [1, 10, 100, 1000, 10000, 100000, 1000000, 10000000],
            [2, 20, 200, 2000, 20000, 200000, 2000000, 20000000],
            [5, 50, 500, 5000, 50000, 500000, 5000000, 50000000],
            [9, 90, 900, 9000, 90000, 900000, 9000000, 90000000],            
        ]
    )
)

array([[ 0.        ,  2.30258509,  4.60517019,  6.90775528,  9.21034037,
        11.51292546, 13.81551056, 16.11809565],
       [ 0.69314718,  2.99573227,  5.29831737,  7.60090246,  9.90348755,
        12.20607265, 14.50865774, 16.81124283],
       [ 1.60943791,  3.91202301,  6.2146081 ,  8.51719319, 10.81977828,
        13.12236338, 15.42494847, 17.72753356],
       [ 2.19722458,  4.49980967,  6.80239476,  9.10497986, 11.40756495,
        13.71015004, 16.01273514, 18.31532023]])

# Округление массивов


In [12]:
M = np.arange(1, 10, 0.003)
A = np.array([2.5, 2.75, 8.1, 9.5])
M, A

(array([1.   , 1.003, 1.006, ..., 9.991, 9.994, 9.997]),
 array([2.5 , 2.75, 8.1 , 9.5 ]))

In [13]:
print(M.round())
print(M.round(2))
print(M.round(3))

[ 1.  1.  1. ... 10. 10. 10.]
[ 1.    1.    1.01 ...  9.99  9.99 10.  ]
[1.    1.003 1.006 ... 9.991 9.994 9.997]


In [14]:
print(np.floor(A))  # округление до целого в меньшую сторону
print(np.ceil(A))   # округление до целого в большуб сторону

[2. 2. 8. 9.]
[ 3.  3.  9. 10.]


# Метематические операции над массивом


In [15]:
print(A)
print(np.add(A, 2.5))           # добавление значения к элементам
print(np.subtract(A, 2.5))      # вычитанние ...
print(np.sum(A))                # суммирование всех значений
print(np.prod(A))                # произведение ...

[2.5  2.75 8.1  9.5 ]
[ 5.    5.25 10.6  12.  ]
[0.   0.25 5.6  7.  ]
22.85
529.03125


# Даты


In [16]:
date_1 = '2020-08-18'
date_2 = '2020-07-18'

In [17]:
date_res = np.datetime64(date_1) - np.datetime64(date_2)
date_res

numpy.timedelta64(31,'D')

# Структурированные списки 

In [18]:
info = np.array(
    [
        ('Anna', 19, 168),
        ('Sam', 33, 175.5),
        ('Pam', 23, 180)
    ],
    dtype=[
        ('name', 'U10'),
        ('age', int),
        ('height', float)
    ]
)
info

array([('Anna', 19, 168. ), ('Sam', 33, 175.5), ('Pam', 23, 180. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f8')])

In [19]:
print(info)
print(info[:2])
print(info[['name', 'age']])

[('Anna', 19, 168. ) ('Sam', 33, 175.5) ('Pam', 23, 180. )]
[('Anna', 19, 168. ) ('Sam', 33, 175.5)]
[('Anna', 19) ('Sam', 33) ('Pam', 23)]


In [20]:
info['age'][0]

19

# Чтение/запись списков из файлов


In [21]:
# запись массивов в файл
np.save('info.npy', info)
np.savetxt('info.txt', info, fmt=['%s', '%d', '%1.2f'], delimiter=';', header='name;age;height')


In [22]:
# загрузка данных 
new_1 = np.load('info.npy')
print(new_1)
new_2 = np.loadtxt('info.txt', delimiter=';', dtype=[
        ('name', 'U10'),
        ('age', int),
        ('height', float)
    ])
print(new_2)


[('Anna', 19, 168. ) ('Sam', 33, 175.5) ('Pam', 23, 180. )]
[('Anna', 19, 168. ) ('Sam', 33, 175.5) ('Pam', 23, 180. )]


In [25]:
np.array2string(info)

"[('Anna', 19, 168. ) ('Sam', 33, 175.5) ('Pam', 23, 180. )]"

In [30]:
info.tolist()

[('Anna', 19, 168.0), ('Sam', 33, 175.5), ('Pam', 23, 180.0)]